### ISSUE TITLE
可以做成这种方式么 这样比较好用

### ISSUE THREAD

**Issue by xuexirong** [TJHello/BillingEasy#1]
类似这个https://github.com/kingofglory/EasyPay
 private void alipay(){
        //实例化支付宝支付策略
        AliPay aliPay = new AliPay();
        //构造支付宝订单实体。一般都是由服务端直接返回。
        AlipayInfoImpli alipayInfoImpli = new AlipayInfoImpli();
        alipayInfoImpli.setOrderInfo("");
        //策略场景类调起支付方法开始支付，以及接收回调。
        EasyPay.pay(aliPay, this, alipayInfoImpli, new IPayCallback() {
            @Override
            public void success() {
                toast("支付成功");
            }

            @Override
            public void failed(int code, String msg) {
                toast("支付失败");
            }

            @Override
            public void cancel() {
                toast("支付取消");
            }
        });
    }

**Comment by TJHello** [comment]
你是指callback这种方式吗？现在就是支持的啊，每个主体方法都带有这样的可选回调。
